# Generated by Django 4.2.7 on 2024-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YG', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
